version: "3"
services:
  be_shop_balo:
    container_name: be_shop_balo
    build:
      context: .
      dockerfile: ./be_shop_balo/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/be_shop_balo
    volumes:
      - ./be_shop_balo:/var/www/be_shop_balo
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - "DB_CONNECTION=pgsql"
      - "DB_PORT=5432"
      - "DB_HOST=db_shop_balo"
      - "DB_DATABASE=shop_balo"
      - "DB_USERNAME=shop_balo"
      - "DB_PASSWORD=qishop_balo@123"

    networks:
      - app-network
    depends_on:
      - db_shop_balo

  db_shop_balo:
    container_name: db_shop_balo
    image: "postgres:14.4-alpine"
    environment:
      - POSTGRES_USER=shop_balo
      - POSTGRES_PASSWORD=qishop_balo@123
      - POSTGRES_DB=shop_balo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:alpine
    volumes:
      - ./docker/volumes/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
  nginx:
    container_name: nginx_be_shop_balo
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./be_shop_balo:/var/www/be_shop_balo
      - ./be_shop_balo/nginx.conf:/etc/nginx/conf.d/be_shop_balo.conf:ro
    networks:
      - app-network
  nginx_fe_shop_balo:
    container_name: nginx_fe_shop_balo
    build:
      context: .
      dockerfile: ./fe_shop_balo/Dockerfile
    ports:
      - "3002:3002"
    # volumes:
    #   # - /var/www/fe_shop_balo:/var/www/fe_shop_balo
    #   - ./fe_shop_balo/nginx.conf:/etc/nginx/conf.d/fe_shop_balo.conf:ro
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
